### ISSUE TITLE
Usage with GatsbyJS

### ISSUE THREAD

**Issue by HarshilShah** [goblindegook/littlefoot#10]
Hey there! Thanks for this repo.

I’m fairly new to the JS/front-end world so forgive me if this is a stupid question, but I’m curious about how you’d set up Littlefoot with Gatsby. I've previously used Bigfoot with Jekyll and had no issues there, but I’m not sure how to set up something like Littlefoot with Gatsby since most things seem to be handled by plugins and don’t really require `<script>`s.

Thank you for your time

**Comment by stuartbreckenridge** [comment]
@HarshilShah Create a `gatsby-browser.js` file in the route of your Gatsby directory. Then (for `bigfootjs` & I assume `littlefoot`):

```
exports.onRouteUpdate = ({location}) => {
  console.log('new pathname', location.pathname)
  $.bigfoot()
}
```

**Note:** Footnotes only render when using `gatsby build && gatsby serve`; they don't render unless you reload a page under `gatsby develop`.
