### ISSUE TITLE
Which version is the latest stable release ?

### ISSUE THREAD

**Issue by brunob** [goblindegook/littlefoot#1264]
Hi, just a quick question. I'm using littlefoot 3.4.1 and i've seen that latest tag is 4.0.6 but https://www.npmjs.com/package/littlefoot?activeTab=versions list this version as a prerelease and link to https://unpkg.com/littlefoot/dist/littlefoot.js mentioned in the readme point to the 3.4.1. So, what's the stable release to use in production, and how can we get 4.X dist files ?

Thx in advance :)

**Comment by goblindegook** [comment]
Hi, yes, it's still a prerelease as there are a few display issues related to element structure/CSS that need to be sorted out.

These issues may or may not affect you, you're able to install the prerelease version and try it out. Pull requests welcome if you're willing to tackle any of them.

**Comment by brunob** [comment]
Thx for the feedback :)
