### ISSUE TITLE
Submit to CDNJS?

### ISSUE THREAD

**Issue by edalzell** [goblindegook/littlefoot#13]
Any chance you could hook this up to CDNJS?

**Comment by goblindegook** [comment]
It's already available on a few CDNs that mirror NPM packages, for example:

* https://unpkg.com/littlefoot/dist/littlefoot.min.js
* https://unpkg.com/littlefoot/dist/littlefoot.css

I'll leave this issue open if anyone is up to submitting littlefoot to this particular CDN.

**Comment by edalzell** [comment]
Perfect, if you could update the readme that would help.

Thanks for your responsiveness!

**Comment by brunob** [comment]
Seems also fixed with 65c3dd2b3139e14eb22e7935a205056b785a7caa as #15 ;)
