### ISSUE TITLE
Footer Disappearing

### ISSUE THREAD

**Issue by IBC-IT** [goblindegook/littlefoot#1317]
I have this working on Squarespace (https://rbseminary.org/2lbc).
However, the footer with the list of footnotes is disappearing.
Any help?

<article>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In cursus turpis massa tincidunt dui. Tortor at auctor urna nunc id cursus metus. Neque ornare aenean euismod elementum nisi quis eleifend quam. Consectetur adipiscing elit duis tristique. Sagittis vitae et leo duis ut diam. Morbi blandit cursus risus at ultrices. <sup id="fnref:1"><a href="#fn:1" class="footnote">[1]</a></sup> Vulputate enim nulla aliquet porttitor lacus. Aliquam ultrices sagittis orci a scelerisque. Placerat in egestas erat imperdiet sed euismod nisi porta. In hac habitasse platea dictumst. Proin fermentum leo vel orci porta non pulvinar. <sup id="fnref:2"><a href="#fn:2" class="footnote">[2]</a></sup></p>
  <aside class="footnotes">
    <hr>
    <ol>
      <li id="fn:1">
        <p>
          This is footnote number 1.
          <a href="#fnref:1" class="reversefootnote">&#160;&#8617;</a>
        </p>
      </li>
      <li id="fn:2">
        <p>
          This is footnote number 2.
          <a href="#fnref:2" class="reversefootnote">&#160;&#8617;</a>
        </p>
      </li>
    </ol>
  </aside>
</article>

**Comment by goblindegook** [comment]
Hi! The library applies a `footnote-print-only` class to the list of footnotes at the bottom. You can override the class definition in your CSS to make the footer visible again.

**Comment by IBC-IT** [comment]
@goblindegook Could you please provide a little more direction on this? What exactly would I modify in the CSS? Not an expert in this, but I can follow directions.

**Comment by IBC-IT** [comment]
I'm adding Custom CSS in Squarespace:

@media not print {
  .footnote-print-only{
    display: inline !important;
  }

However, this does not seem to do the trick.

**Comment by IBC-IT** [comment]
> Hi! The library applies a `footnote-print-only` class to the list of footnotes at the bottom. You can override the class definition in your CSS to make the footer visible again.

@goblindegook Any further instruction on this? Have been struggling to get this working for several days. Thank you!
