### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by edalzell** [goblindegook/littlefoot#14]
Here is the HTML output:
```html
<p>this is a test of a footnote<sup id="fnref:1"><a href="#fn:1" class="footnote-ref">1</a></sup></p>

<div class="footnotes">
<hr />
<ol>

<li id="fn:1">
<p>testing&#160;<a href="#fnref:1" class="footnote-backref">&#8617;&#xFE0E;</a></p>
</li>

</ol>
</div>
```

the Littlefoot JS is loaded and I have the following in my JS:
```js
var littlefoot = require('littlefoot').default;

littlefoot();
```

When I click on a footnote nothing pops up. How can I debug this?

Thanks

**Comment by edalzell** [comment]
I simplified to your default code and inlining everything:
```

<main class="flex-1">
--
  | <p>
  | <sup id="fnref:2">
  | <a href="#fn:2" rel="footnote">2</a>
  | </sup>
  | </p>
  |  
  | <!-- Footnote List -->
  | <div class="footnotes">
  | <ol>
  | <li class="footnote" id="fn:2">
  | <p>footnote. <a href="#fnref:2" title="return to article"> ↩</a></p>
  | <p></p>
  | </li>
  | </ol>
  | </div>
  | <script src="/site/themes/dl/js/littlefoot.min.js"></script>
  |  
  | <script>
  | var littlefoot = require('littlefoot').default;
  |  
  | littlefoot();
  |  
  | </script>


```

still doesn't work

**Comment by goblindegook** [comment]
Already resolved via Twitter, but for reference, the following example has it working with littlefoot from a CDN:

https://codepen.io/goblindegook/pen/oPNzGE

**Comment by candidexmedia** [comment]
> Already resolved via Twitter, but for reference, the following example has it working with littlefoot from a CDN:
> 
> https://codepen.io/goblindegook/pen/oPNzGE

I'm having trouble getting the hover to work on the CDN codepen. What should I add?
