### ISSUE TITLE
Exclude postcss.config.js from package

### ISSUE THREAD

**Issue by fshowalter** [goblindegook/littlefoot#1709]
Hi,

Congrats on the 4.0 release! Looks like lots of work went into this out the door. I think you missed one bit, however. By including the postcss.config.js in the package root, it'll get picked up by anyone referencing the CSS in the dist (such as Gatsby) and using postcss-loader (again, Gatsby).

https://webpack.js.org/loaders/postcss-loader/#config-cascade

This wouldn't be too much of a problem, except it includes a "plugins" section which means the loader will try and load those plugins and error when they aren't found (example: stylelint). 

Removing the postcss.config.js file from node_module/littlefoot resolves the problem.

**Comment by goblindegook** [comment]
Merged, thanks for the patch!
