### ISSUE TITLE
Current parsing of ‘li’ inserts unexpected paragraph elements

### ISSUE THREAD

**Issue by dato** [goblindegook/littlefoot#187]
Hello!

I noticed that my littlefoot popups have leading and trailing `<p>` that are not present in the original HTML.

In other words, for a footnote consisting —in the source HTML— of a single paragraph, the popup content has three.

With some work, I was able to trace it to the way my Markdown engine generates the footnotes: with a newline between the `<li>`element, and its first `<p>`.

I prepared an example to show what I mean: https://jsfiddle.net/gzsnhd7x/show. The second popup contains unexpected `<p>` elements.

Many thanks in advance!

**Comment by goblindegook** [comment]
Thanks for reporting, fixed in v3.2.5.
