### ISSUE TITLE
Documentation says `allowDuplicates` default is `false` but is actually `true`.

### ISSUE THREAD

**Issue by jasonanthonyguy** [goblindegook/littlefoot#1936]
This was causing me to pull my hair out before realizing the issue. I’m not sure which is the preferred default, either works for me, as long as it’s accurately documented.

Docs: https://github.com/goblindegook/littlefoot/blob/07d16e4da7a01ee9e490e685bfdfa3bc3e23093b/README.md?plain=1#L169

Settings: https://github.com/goblindegook/littlefoot/blob/07d16e4da7a01ee9e490e685bfdfa3bc3e23093b/src/settings.ts#L14

(Now that I realized this, it works great!)

**Comment by goblindegook** [comment]
Fixed, thank you for spotting it!
