### ISSUE TITLE
Library doesn't work on gatsby's development server / build

### ISSUE THREAD

**Issue by eyalroth** [goblindegook/littlefoot#26]
As of the latest few gatsby versions, the usage instructions for gatsby in the `README.md` no longer work for gatsby's development server (`gatsby develop`), but only for production builds (`gatsby build`).

I believe this is caused because when the `onRouteUpdate` function is invoked, the HTML is yet to contain the actual page content, but rather the `gatsby-focus-wrapper` div is empty (see https://github.com/gatsbyjs/gatsby/issues/14098).

One workaround is to call the `littlefoot` method with a timeout, but that is a rather messy and undesirable workaround. For now, I compromised on invoking the method on my main "page" component:

```js
class Page extends React.Component {
  componentDidMount() {
    if (typeof window !== 'undefined') {
        const littlefoot = require('littlefoot').default
        littlefoot()
    }
  }
}
```

It is important to `require` the module only inside of the condition, since this action involves invoking `window` and thus will fail the production build if it is made outside the condition (say, at the top of the file with `import`). In fact, according to [gatsby's documentation](https://www.gatsbyjs.org/docs/debugging-html-builds/), it is sufficient to invoke this part inside the `componentDidMount` and there is no need for the `window` check.

Perhaps there is an alternative, more elegant gatsby API / "hook" that works too, but I'm not familiar enough with their API.

**Comment by goblindegook** [comment]
This appears to be a bug in Gatsby, a similar problem is described here: https://github.com/gatsbyjs/gatsby/issues/17946

**Comment by goblindegook** [comment]
It seems to have been fixed, as one of my sites integrating `littlefoot` via `onRouteUpdate` is now correctly working in development mode.
