### ISSUE TITLE
no release since 3.1.3

### ISSUE THREAD

**Issue by brunob** [goblindegook/littlefoot#28]
96bce8188bc1851cd579b619278073ffd54acc94 mention version 3.1.5, but there is no release/tag since 3.1.3 cf https://github.com/goblindegook/littlefoot/releases

**Comment by goblindegook** [comment]
Switch to "Tag" view. There are no release notes because nothing changed for the user, it was just a couple of refactors that made the library a little smaller.

**Comment by brunob** [comment]
'k thx for the info :)
