### ISSUE TITLE
Release a new version… maybe 1.0?

### ISSUE THREAD

**Issue by bdesham** [goblindegook/littlefoot#3]
I got my website all set up to use 1.0.0-alpha14. I noticed a bug—clicking the button for the active footnote does not close the popover—but when I downloaded master to try to fix the bug it was already fixed. Would you consider releasing a new version with this change in place? The project has been in its current form for a while now, so maybe it’s even time to release a “final” 1.0.0 version?

**Comment by bdesham** [comment]
…although it also seems that, under the newest master version, none of my footnotes have any content. I’ll try to track down the cause.

**Comment by goblindegook** [comment]
I should come in here more often. Version 1.0.0 released!

**Comment by goblindegook** [comment]
And thanks for your patience!

**Comment by bdesham** [comment]
Awesome, thank you! 👍
