### ISSUE TITLE
Problem with gatsby production build

### ISSUE THREAD

**Issue by xavdid** [goblindegook/littlefoot#338]
Hi there! I love bigfoot, so I'm really glad you decided to take this on.

I'm seeing some odd behavior when using this w/ Gatsby. During the development build, everything works as expected:

<img width="508" alt="Screen Shot 2020-06-07 at 5 15 32 PM" src="https://user-images.githubusercontent.com/1231935/83983359-883d1080-a8e2-11ea-89b6-a02cfede243d.png">

During the production build, something goes wrong. It looks like the correct CSS isn't being applied and/or the regular markdown isn't being removed properly. You'll note that on the production page, the original footnotes are at the bottom of the page. 

<img width="842" alt="Screen Shot 2020-06-07 at 5 16 07 PM" src="https://user-images.githubusercontent.com/1231935/83983371-a0149480-a8e2-11ea-8081-89044074da19.png">

You can see that live here: https://xavd.id/blog/post/an-ode-to-kobo/

I've got basically the exact example from the docs, plus the default numeric button markup: 

https://github.com/xavdid/xavdid.github.io/blob/d3de8fc3ca9060335f1be8f6572f32246b335675/gatsby-browser.js

I tried it without the button markup it had the same result (except that the button was blank, not with a number). 

I'm using `gatsby-plugin-mdx` (which uses remark under the hood) for markdown parsing and a recent (though not latest) version of gatsby (to get around a separate issue). 

Any ideas you have are much appreciated!

**Comment by goblindegook** [comment]
JS is working fine, but CSS is not being included. It seems to be an issue with Gatsby itself, there's at least an issue describing your exact problem: https://github.com/gatsbyjs/gatsby/issues/5758 (closed due to inactivity).

If you copy the CSS file from the littlefoot module to your project and include it there, would that work around the issue?

**Comment by xavdid** [comment]
Ah, great call! I changed `import "littlefoot/dist/littlefoot.css";` to `require("littlefoot/dist/littlefoot.css");` and it worked like a charm. So odd.

Thanks a bunch!
