### ISSUE TITLE
Goldmark compatibility?

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [goblindegook/littlefoot#358]
Hi!
I'm currently using the [Academic theme](https://sourcethemes.com/academic/) for [Hugo](https://gohugo.io), which uses [Goldmark](https://github.com/yuin/goldmark/) by default.

I'm trying to make `littlefoot` work but no luck yet.

I haven't figured out the problem yet but any help would be greatly appreciated.

Thanks!

**Comment by goblindegook** [comment]
The markup generated by Hugo should work out of the box. Might be worth checking if the footnote extension is enabled on Goldmark.

While I don't use the Academic theme, my personal website (https://github.com/goblindegook/goblindegook.com) is built on Hugo as well and it uses littlefoot. Hope it helps.

**Comment by rodrigoalcarazdelaosa** [comment]
My bad, (I thought) I was overriding one of the templates of my theme but I wasn't (wrong path). Now `littlefoot` is working although it seems to conflict with the [asides extension of the Academic theme](https://sourcethemes.com/academic/docs/writing-markdown-latex/#asides).

This is what happens:

Before clicking the footnote:
![image](https://user-images.githubusercontent.com/9049533/84951069-29507600-b0f0-11ea-8879-56dd9a5562b5.png)

After clicking the footnote (which seems to be using part of the CSS associated with the `asides`):
![image](https://user-images.githubusercontent.com/9049533/84951084-32d9de00-b0f0-11ea-9f1e-54d1f41d2274.png)

It seems that the [Academic theme](https://sourcethemes.com/academic/) is overriding `littlefoot` CSS. I will need to tweak that, hope it's possible.

Thanks in advance!
Rodrigo

**Comment by goblindegook** [comment]
Academic is being a bit naughty there, using almost blanket selectors like `.article-style aside`, but you should still be able to override everything by adding your own CSS properties.
