### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by sensaetions** [goblindegook/littlefoot#5]
Hello I've been trying to find a responsive footnote solution and found BigfootJS. But after discovering that BigfootJS isn't compatible with jQuery 3, I've found littlefoot.

I followed the instructions but littlefoot isn't working. I've installed the plugin via NPM, included it in my project files, added the styles via SCSS and compiled it. Here's my setup
HTML:
`<sup id="fnref:1"><a href="#fn:1" rel="footnote">1</a></sup>`
~~~~
<div class="footnotes">
    <ol class="list list--ordered">
        <li class="list__item footnote" id="fn:1">
            <p>footnote for disclosure #1.
               <a href="#fnref:1" title="return to article">
                  <i class="fa fa-level-up"></i>
               </a>
            <p>
        </li>
    </ol>
</div>
~~~~

JS:
~~~~
var littlefoot = require('littlefoot').default;
var littlefootOptions = littlefoot({
    allowDuplicates: true,
    allowMultiple: true,
    activateOnHover: true,
    dismissOnUnhover: true,
    hoverDelay: 100,
    preventPageScroll: false,
});
littlefoot(littlefootOptions);
~~~~

Can you help?

**Comment by bdesham** [comment]
It looks like you’re calling the `littlefoot` function an extra time. Instead of

    var littlefootOptions = littlefoot({
        …
    });

try

    var littlefootOptions = {
        …
    };

Let us know if that solves your problem. If not, could you post more detailed information about what isn’t working? Are your footnotes just completely unmodified from the way they looked before?

**Comment by sensaetions** [comment]
Thank you for the quick response!
I updated my options as you've specified and still not working. The only other different thing that I made from the README instructions was added semicolons `;` after each line of code. Is there something I am doing wrong with my code?

Here's the codepen example:
https://codepen.io/sensaetions/pen/RZJEbX

Also, is there an easier way of linking to the dist versions of the stylesheet and js?

**Comment by bdesham** [comment]
I took another look. The `littlefoot` variable should *already* be defined for you if you’ve included littlefoot.min.js, so all you should have to do is

    var littlefootOptions = {…};
    littlefoot.default(littlefootOptions);

Give that a try. (You don’t have to use the semicolons if you don’t want to; it doesn’t make a difference in this case.)

I don’t think there is an easier way to link to the dist versions. It would be possible to have Travis (or another CI system) build the project and then include the dist versions in the released tarballs, but even in that case you wouldn’t be able to just link to them from another website—you’d have to download the tarball yourself, extract the JavaScript file, and host it somewhere.

You can *link to* a given footnote ID as many times as you want, but no two elements on your page should ever have the same value for their `id` attribute. That’s invalid HTML and could lead to all kinds of confusing behavior. Your Codepen example doesn’t seem to be doing that, though—it looks fine to me. I’m not completely sure what you’re asking here :-)

**Comment by sensaetions** [comment]
Hello and thanks for the quick response,
I've adjusted my JS code on my codepen and it still doesn't work. Could you take a look and see what could be missing?
The CSS and minified JS plugin is linked.

**Comment by bdesham** [comment]
Take a look at [this forked version of the Codepen](https://codepen.io/anon/pen/vJrbGg). The entire JavaScript is

```
// littlefoot plugin linked

var littlefootOptions = {
    allowDuplicates: true,
    allowMultiple: true,
    activateOnHover: true,
    dismissOnUnhover: true,
    hoverDelay: 100,
    preventPageScroll: false,
}

littlefoot.default(littlefootOptions)
```

This works in my browser.

(I have pointed it to a copy of Littlefoot that I’m hosting, but that link will stop working in a day or so.) I’m not aware of an official working demo, unfortunately.

**Comment by sensaetions** [comment]
Hello,
Thank you for the forked codepen. After I changed my link to the littlefoot plugin you hosted, I can see the change. Then I used Kaleidoscope app to compared the js file that's provided in the NPM library dist folder with the file you're hosting. There are noticeable differences between the two copies -- which I'm attaching here for your comparison as well.  Is there any way to update the files that is available from NPM?

[littlefootjs-for-comparison.zip](https://github.com/goblindegook/littlefoot/files/1247265/littlefootjs-for-comparison.zip)

**Comment by bdesham** [comment]
Ah. I forgot that I’m using the latest “master” version, which has some changes compared to version 1.0.0-alpha.14, the newest one available on NPM. I opened issue #3 about this a while ago but unfortunately it seems that the maintainer of this project is no longer issuing releases or merging PRs.

My advice is to download the latest code, build it yourself, and use that, instead of trying to get it from NPM. The alternative would be to tough it out with the latest released version. If you do that you’ll want to refer to [the README as of version 1.0.0-alpha.14](https://github.com/goblindegook/littlefoot/tree/v1.0.0-alpha.14), not the current README, since there are some small differences in how your Littlefoot code needs to look.

**Comment by sensaetions** [comment]
Okidoki. I looked at the README for version 1.0.0-alpha.14 and it looked identical to the master branch. However, I did download master and built it to use instead of installing from npm.

Do you have any ideas in regards to my question about using numeric superscripts instead of triple dots?  Do I need to modify the script to use the `data-footnote-number="1"` instead?

**Comment by goblindegook** [comment]
@sensaetions You got the right idea for adding numeric callouts instead of the default ellipsis, the trick is to do it via templates.

As for your last question, I'm afraid that using the original indicators in the template is not currently supported.

**Comment by sensaetions** [comment]
Hi Luís, thanks for the response.  Do you think there's the possibility of updating this plugin to allow for the original numerical indicators in the `<sup>` tag to be used in the templates?

Thanks for all of your help so far!
