### ISSUE TITLE
Popover animation work only the first time

### ISSUE THREAD

**Issue by elias94** [goblindegook/littlefoot#505]
Hi, I'm using _littlefoot_ last version with the following configuration. The animation works only the first time opening the popover. Also trying to activate the _hover_ feature I have the same behavior.
``` javascript
littlefoot({
    // activateOnHover: true,
    // dismissOnUnhover: true,
    buttonTemplate: `
      <button
        aria-expanded="false"
        aria-label="Footnote <% number %>"
        class="littlefoot-footnote__button"
        id="<% reference %>"
        title="See Footnote <% number %>"
      />
        <% number %>
      </button>
    `,
})
```

**littlefoot**: `"littlefoot": "^3.4.0"`
**Jekyll** :`"jekyll", "~> 4.1.1"`
**Chrome**: `Version 85.0.4183.102 (Official Build) (64-bit)`
**macOS Catalina**: `10.15.6`

**Comment by goblindegook** [comment]
Thanks, @elias94, will look into it.

**Comment by goblindegook** [comment]
Thanks again for reporting, a fix will be included in the next release.
