### ISSUE TITLE
Footnotes are broken on smartphone in landscape mode

### ISSUE THREAD

**Issue by pangolinbubonique** [goblindegook/littlefoot#683]
Hi, when you use the footnotes on a smartphone in landscape mode, the footnotes don't display well. Noticed on google chrome, firefox and safari). But when testing on PC with a window of the same proportions, it works.

By the way, I admit it is not the best way to use footnotes, a good feature would be to display them on the right side, the same way they are displayed at the bottom of the screen when you are in classic portrait mode.

**Comment by goblindegook** [comment]
Hi @pangolinbubonique, which version of littlefoot are you running?

**Comment by pangolinbubonique** [comment]
Hi, I was running a custom version, but I tried with 4.0.0-6 and the same behaviour occurs.

Here is a screenshot with version 4.0.0-6:
![a](https://user-images.githubusercontent.com/77063088/107120842-96876600-688f-11eb-861d-e1720f18730c.jpg)

**Comment by goblindegook** [comment]
Interesting, I'd never seen that before. Thanks for filing the issue!

**Comment by goblindegook** [comment]
It appears the content area of the popover is exactly the same width as the button. Something's preventing the popover content from going full width (and centred).

Does the problem persist if you reopen the footnote, or scroll up and down on the document?

**Comment by pangolinbubonique** [comment]
Yes it persists.

I just noticed that a normal behaviour goes back when you refresh the page while being already in landscape mode. In fact the problem occurs precisely when you load the page in portrait mode, and then flip in landscape mode by just moving the smartphone.

Oh and just another thing which is more a detail, the arrow informing that you can scroll down in the note doesn't disappear when you end scrolling, contrary to on PC browsers.

**Comment by goblindegook** [comment]
This issue was reported in #1702 with a potential fix, version `4.0.0-11` hopefully addresses the problem.
