### ISSUE TITLE
Backlinks are broken

### ISSUE THREAD

**Issue by yeefom** [goblindegook/littlefoot#767]
Hello,

This [commit](https://github.com/goblindegook/littlefoot/commit/6d1841c0c107fe4b3809f37f20ead4d367a90d99) introduced a change that prefixes footnote button id with `lf-`. According to the commit notes, is is to avoid id duplication. It however broke backlink’s functionality as backlink is still looking for the original id without the prefix. 

Since littlefoot hides backlinks along with the whole footnote section by default, this is only a problem for users who choose to unhide the footnote section.

I’m not sure if the prefix helps with id duplication much since the duplication probably commonly happens when the original ids themselves have duplication. Tagging the original author of the PR @biou — do you think we could remove the prefix?

I’m happy to open a PR either for removing the prefix or another suggested fix.

**Comment by biou** [comment]
Hello, 
indeed duplicate ids are not valid html and can impact accessibility (see WCAG 4.1.1)
Could you please give me more details about your use case? Or a code example? 
So far I just built master and cannot reproduce your issue.

**Comment by goblindegook** [comment]
I had to double check but we don't alter the original HTML at all beyond applying a `footnote-print-only` class. We don't change those IDs at all. The backlink normally points to the original `<sup>` element that contains the footnote callout, it was never supposed to reference the button.

The problem here might be that the `sup` element has the `footnote-print-only` class, and therefore `display: none`, breaking the backlink.

One way around this might be to redefine the `footnote-print-only` style into something like:

```css
.footnote-print-only {
  display: initial;
  visibility: hidden;
  width: 0;
}
```

**Comment by biou** [comment]
But AFAIK the backlink itself is also hidden with `display: none`.  The only way to display the backlink and not the sup would be through overloading the styles, correct? In this case, why not overload also the styles of the sup.

I tested the print styles with the Firefox dev tools and the backlink is working properly here.

**Comment by goblindegook** [comment]
> But AFAIK the backlink itself is also hidden with display: none. The only way to display the backlink and not the sup would be through overloading the styles, correct?

Correct. It seems this can be solved by overriding the styles, there's nothing we can do with the default stylesheet (which hides both elements).

**Comment by yeefom** [comment]
Thank you both. You are right - backlink should not refer to the button. My setup was working before by accident because button had the same id as `<sup>`.

This is the CSS I used to hide  `<sup>` entirely from the page while keeping it in the DOM in case it could be useful for others.

```
sup.footnote-print-only {
  display: inline-flex;
  visibility: hidden;
  width: 0;
}
```
