### ISSUE TITLE
Issue on mobile

### ISSUE THREAD

**Issue by simardcasanova** [goblindegook/littlefoot#9]
Hello there,

I installed littlefoot.js on a WordPress website. I used the solution offered here: https://github.com/goblindegook/littlefoot/issues/8 (more specifically, I replicated the demo here: https://github.com/goblindegook/littlefoot/issues/8#issuecomment-414358376).

It works fine on desktop and tablet, but when the footnotes have to be displayed in full width (on mobile mostly), the display breaks. See this screenshot:

![img_4468](https://user-images.githubusercontent.com/739940/44800637-33218600-abb7-11e8-8b50-a85bbb3b9f5f.jpg)

I tried to use another WordPress theme to see if there is any incompatibility between my current theme and littlefoot, but nothing changed. I also deactivated another plugin I used in the past to display footnotes.

Any idea what I could do to fix this?

Thank you very much, and great work on this script!

**Comment by goblindegook** [comment]
Thanks for reporting this, I've pushed a fix that seems to correct (at least) the issue on the [Codepen demo](https://codepen.io/goblindegook/pen/oPNzGE). Can you check version 1.0.6, please?
