### ISSUE TITLE
Title tooltip on footnote button hover partially blocks footnote tooltip

### ISSUE THREAD

**Issue by StevenTammen** [goblindegook/littlefoot#970]
Here is how I am initializing Littlefoot

```html
<script src="/js/littlefoot.js" type="application/javascript" ></script> 
<script type="application/javascript"> littlefoot.default({
  activateOnHover: true,
  dismissOnUnhover: true,
  hoverDelay: 200,
}) </script>
```

I like having the footnotes automatically dismissed so as to be able to move your mouse around a page without having footnotes stay popped-up if you hover over one incidentally when scrolling (e.g.). I think this sort of UX is superior.

One side effect of using the library this way, however, is that when viewing a footnote, the user needs to keep their mouse cursor over the footnote button or the footnote tooltip so that it won't be dismissed. Having their mouse cursor over the tooltip blocks the text a bit, but so too does having the cursor over the footnote button, because of the title tooltip triggering as well on hover. Here is what I mean:

![littlefoot-title-tooltip-blocking-footnote-tooltip](https://user-images.githubusercontent.com/14948260/142782631-dec5d931-e2b1-4809-8245-d52a8a7aefc3.gif)

Is there a good way to prevent this behavior out of the box (preferably by disabling the title tooltip when hovering over the footnote button, leaving just the footnote tooltip)? I'm sure there is a way to do it in a somewhat kludgy modify-the-DOM-at-render-time sort of way, but I'm just curious if I have failed to find a configuration setting that might help in this regard.

Some markdown renderers may not add such a title attribute, but the two I have tried (one for the static site generator I use, and another for a JavaScript library that turns Markdown into presentation slides) have added a title attribute, leading to this issue.

Any thoughts?

**Comment by StevenTammen** [comment]
I have figured out a way to solve my own issue here.

First of all, I verified that the title attribute is not necessarily required for accessibility (which I suppose was why I didn't think to just get rid of it earlier). For example:

- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA
- https://stackoverflow.com/a/29853683
- https://stackoverflow.com/a/13382920

Secondly, I realized that my understanding was incorrect, and it was not a static site generator or other renderer generating the titles, but Littlefoot itself. This means I have the ability to remove the title attribute, thereby solving the problem. I did this by using a buttonTemplate:

```html
<script src="/js/littlefoot.js" type="application/javascript" ></script> 
<script type="application/javascript"> littlefoot.default({
  activateOnHover: true,
  dismissOnUnhover: true,
  hoverDelay: 200,
  buttonTemplate: `
	<button
	aria-label="Footnote <% number %>"
	class="littlefoot__button"
	id="<% reference %>"
	/>
	<% number %>
	</button>
  `,
}) </script>
```

Now, the styling was all wonky when I switched to number buttons. I was too lazy to debug exactly why, so just set out to style things explicitly. I could not get the [CSS custom properties](https://github.com/goblindegook/littlefoot#example) to work at all, so just ended up using the explicit class:

```css
.littlefoot__button {
	background-color: #dddddd;
	color: #777777;
	height: 1rem;
	padding: 0rem 0.8rem;
	margin: 0rem 0.1rem;
	border: none;
	border-radius: 10px;
	vertical-align: middle;
	display: inline-flex;
  	align-items: center; 
}
```

Interestingly, on my site, the `buttonTemplate` supposed to exactly follow the unset default (as stated [in this section](https://github.com/goblindegook/littlefoot#buttontemplate)) showed up quite differently in practice. On first inspection, it looks like the template given there lacks the `littlefoot-footnote__button__ellipsis` CSS class that contains some of the appropriate styling, but even adding that did not fix everything. It could be something peculiar with my own inherited styles. I do not know.

In any case, I am happy with the output of all this:

![reworked-implementation](https://user-images.githubusercontent.com/14948260/142787873-f5d92b6c-213f-4069-af38-25d8d1d87146.gif)

I'm still interested in feedback on perhaps the way I accomplished this, and the problem in general. However, feel free to close the issue if you think it appropriate.

**Comment by goblindegook** [comment]
Looks good, that's exactly how you override default settings.

CSS properties working might depends on how your CSS is being compiled --- if the asset builder inlines the custom properties then I imagine it might be impossible to redefine them. Also bear in mind that CSS properties are a feature of the upcoming version 4.0, they won't work unless you install `littlefoot` with an explicit prerelease version.
